sudo: required

language: node
node:
  - 0.10

install:
  - examples/test/travis-setup.sh

env:
  - LANGUAGE=python EXT=py
  - LANGUAGE=python EXT=py BIN=python3
  - LANGUAGE=php EXT=php
  - LANGUAGE=node EXT=js
  - LANGUAGE=perl EXT=pl
  - LANGUAGE=ruby EXT=rb

script: 
- examples/test/run-tests.sh

before_install:
- openssl aes-256-cbc -K $encrypted_d93385c721d4_key -iv $encrypted_d93385c721d4_iv
  -in .edgerc.enc -out $HOME/.edgerc -d
  
secure: "amqiQ/BTh53HbwqZP8iYopzSCIvVDI4xT/FrmRzrF1Dfhd6XxcvdlLnhPXawiIsmEMF0KH1ZLjPqrpek1M20tXUlC3u2XCFVtUjG2u5jYfP3vHEPBUEd+bvF9lnaHukAmoc7KP+pzhBSwZ2IbpW3XXLu9Jpg62p+Fm/opPeRen8="
